name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 23

    - name: Install dependencies
      working-directory: app
      run: npm install

    - name: Build web app
      working-directory: app
      run: npm run build

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: '33.0.2'
        target: 'android-33'

    - name: Build APK
      working-directory: app/android
      run: ./gradlew assembleDebug

    - name: Rename APK
      working-directory: app/android/app/build/outputs/apk/debug/
      run: mv app-debug.apk OrbWallet.apk

    - name: Upload APK to GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: apk
        release_name: APK Build
        draft: false
        prerelease: false
        files: app/android/app/build/outputs/apk/debug/OrbWallet.apk
